#!/bin/bash

#Add implementation for _memcpy
echo "char *_memcpy(char *dest, char src, unsigned int n) {" >> _memcpy.c
echo " / Your code here */" >> _memcpy.c
echo "}" >> _memcpy.c

#Add implementation for _strchr
echo "char *_strchr(char s, char c) {" >> _strchr.c
echo " / Your code here */" >> _strchr.c
echo "}" >> _strchr.c

#Add implementation for _strspn
echo "unsigned int _strspn(char *s, char accept) {" >> _strspn.c
echo " / Your code here */" >> _strspn.c
echo "}" >> _strspn.c

#Add implementation for _strpbrk
echo "char *_strpbrk(char *s, char accept) {" >> _strpbrk.c
echo " / Your code here */" >> _strpbrk.c
echo "}" >> _strpbrk.c

#Add implementation for _strstr
echo "char *_strstr(char *haystack, char needle) {" >> _strstr.c
echo " / Your code here */" >> _strstr.c
echo "}" >> _strstr.c
